#!/usr/bin/python

import fileinput
import sys

import projparser


lines = [line for line in fileinput.input()]

sections = projparser.parse(lines)

# dump top-level parents recursively
for section in sections:
	projparser.dump_section(section)
